version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    
  backend:
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
  
volumes:
  mongo-data:

